package drawio

import (
	"fmt"
	"strings"

	"github.com/OverloadBlitz/cloudcent-cli/internal/api"
	"github.com/OverloadBlitz/cloudcent-cli/internal/pulumi/resources"
)

const SpecVersion = 1

// Spec is the persisted side-file describing one drawio diagram's billable
// resources. Generated by `diagram init`, hand-edited by the user, then
// consumed by `diagram estimate`.
type Spec struct {
	Version    int             `yaml:"version"`
	Defaults   SpecDefaults    `yaml:"defaults"`
	Components []SpecComponent `yaml:"components"`
}

// SpecDefaults supplies fallback values applied to any component that doesn't
// override them locally.
type SpecDefaults struct {
	Provider string `yaml:"provider"`
	Region   string `yaml:"region"`
}

// SpecComponent is one row in the spec, joined to a drawio cell by its ID.
type SpecComponent struct {
	ID        string            `yaml:"id"`
	Label     string            `yaml:"label"`
	Service   string            `yaml:"service"`
	Provider  string            `yaml:"provider,omitempty"`
	Region    string            `yaml:"region,omitempty"`
	Attrs     map[string]string `yaml:"attrs,omitempty"`
	Price     string            `yaml:"price,omitempty"`
	NoPricing bool              `yaml:"noPricing,omitempty"`
}

// lookupDrawioDef returns the DrawioResourceDef for a draw.io service suffix.
// Lookup is case-insensitive. Returns (def, true) when found.
func lookupDrawioDef(service string, meta *api.MetadataResponse) (api.DrawioResourceDef, bool) {
	if meta == nil || len(meta.DrawioResources) == 0 {
		return api.DrawioResourceDef{}, false
	}
	key := strings.ToLower(strings.TrimSpace(service))
	// Exact match first.
	if def, ok := meta.DrawioResources[key]; ok {
		return def, true
	}
	// Case-insensitive fallback.
	for k, def := range meta.DrawioResources {
		if strings.ToLower(k) == key {
			return def, true
		}
	}
	return api.DrawioResourceDef{}, false
}

// ToDecoded converts a SpecComponent into the resources.DecodedResource shape
// consumed by estimate.EstimateAllResources.
//
// meta is required to resolve the DrawioResourceDef for the component's
// service. When meta is nil or the service is not found in DrawioResources,
// the component is treated as NoPricing.
func (s SpecComponent) ToDecoded(defaults SpecDefaults, meta *api.MetadataResponse) (resources.DecodedResource, error) {
	provider := s.Provider
	if provider == "" {
		provider = defaults.Provider
	}
	region := s.Region
	if region == "" {
		region = defaults.Region
	}

	if s.NoPricing {
		return resources.DecodedResource{
			Provider:  provider,
			Region:    region,
			Name:      displayName(s),
			RawType:   s.Service,
			Props:     specProps(s, region),
			NoPricing: true,
		}, nil
	}

	def, found := lookupDrawioDef(s.Service, meta)
	if !found {
		// Service not in metadata — treat as no-pricing.
		return resources.DecodedResource{
			Provider:  provider,
			Region:    region,
			Name:      displayName(s),
			RawType:   s.Service,
			Props:     specProps(s, region),
			NoPricing: true,
		}, nil
	}

	// Use provider from def when not overridden by spec.
	if provider == "" && def.Provider != "" {
		provider = def.Provider
	}

	// Build attrs: apply defaults from def, then overlay user-supplied values,
	// then apply value maps from def.
	attrs := make(map[string]string, len(def.Attrs))

	for canonicalName, attrDef := range def.Attrs {
		val := ""

		// User-supplied value takes priority.
		if v, ok := s.Attrs[canonicalName]; ok {
			val = strings.TrimSpace(v)
		}

		// Fall back to default from metadata.
		if val == "" && attrDef.Default != "" {
			val = attrDef.Default
		}

		// Apply value translation map if present.
		if val != "" && len(attrDef.Map) > 0 {
			val = applyDrawioValueMap(val, attrDef.Map)
		}

		if val != "" {
			attrs[canonicalName] = val
		}
	}

	// Validate: every attr defined in the def must have a value.
	var missing []string
	for canonicalName := range def.Attrs {
		if strings.TrimSpace(attrs[canonicalName]) == "" {
			missing = append(missing, canonicalName)
		}
	}
	if len(missing) > 0 {
		return resources.DecodedResource{}, fmt.Errorf(
			"component %q (%s) missing required attrs: %s",
			displayName(s), s.Service, strings.Join(missing, ", "),
		)
	}

	return resources.DecodedResource{
		Provider:    provider,
		Region:      region,
		Service:     def.Product,
		Name:        displayName(s),
		RawType:     s.Service,
		Attrs:       attrs,
		Props:       specProps(s, region),
		PriceFilter: s.Price,
	}, nil
}

// applyDrawioValueMap translates a value using the provided map.
// Lookup is case-insensitive; if no mapping matches the original value is returned.
func applyDrawioValueMap(val string, m map[string]string) string {
	if mapped, ok := m[val]; ok {
		return mapped
	}
	lower := strings.ToLower(val)
	for k, v := range m {
		if strings.ToLower(k) == lower {
			return v
		}
	}
	return val
}

func displayName(s SpecComponent) string {
	if strings.TrimSpace(s.Label) != "" {
		return s.Label
	}
	return s.ID
}

func specProps(s SpecComponent, region string) map[string]string {
	props := map[string]string{}
	if region != "" {
		props["region"] = region
	}
	if s.Service != "" {
		props["service"] = s.Service
	}
	for k, v := range s.Attrs {
		if strings.TrimSpace(v) == "" {
			continue
		}
		props[k] = v
	}
	return props
}
