package drawio

import (
	"fmt"
	"strings"

	"github.com/OverloadBlitz/cloudcent-cli/internal/api"
	"github.com/OverloadBlitz/cloudcent-cli/internal/pulumi/resources"
)

const SpecVersion = 1

// Spec is the persisted side-file describing one drawio diagram's billable
// resources. Generated by `diagram init`, hand-edited by the user, then
// consumed by `diagram estimate`.
type Spec struct {
	Version    int             `yaml:"version"`
	Defaults   SpecDefaults    `yaml:"defaults"`
	Components []SpecComponent `yaml:"components"`
}

// SpecDefaults supplies fallback values applied to any component that doesn't
// override them locally.
type SpecDefaults struct {
	Provider string `yaml:"provider"`
	Region   string `yaml:"region"`
}

// SpecComponent is one row in the spec, joined to a drawio cell by its ID.
type SpecComponent struct {
	ID        string            `yaml:"id"`
	Label     string            `yaml:"label"`
	Service   string            `yaml:"service"`            // short service suffix, e.g. "ec2_instance"
	ShapeKey  string            `yaml:"shapeKey,omitempty"` // full normalised shape key, e.g. "mxgraph.aws4.ec2_instance"
	Provider  string            `yaml:"provider,omitempty"`
	Region    string            `yaml:"region,omitempty"`
	Attrs     map[string]string `yaml:"attrs,omitempty"`
	Price     string            `yaml:"price,omitempty"`
	NoPricing bool              `yaml:"noPricing,omitempty"`
}

// lookupDrawioDef returns the DrawioResourceDef for a draw.io component.
// shapeKey is the full normalised shape key, e.g. "mxgraph.aws4.ec2_instance".
// Lookup is case-insensitive. Returns (def, true) when found.
func lookupDrawioDef(shapeKey string, meta *api.MetadataResponse) (api.DrawioResourceDef, bool) {
	if meta == nil || len(meta.DrawioResources) == 0 {
		return api.DrawioResourceDef{}, false
	}
	key := strings.ToLower(strings.TrimSpace(shapeKey))
	// Exact match first.
	if def, ok := meta.DrawioResources[key]; ok {
		return def, true
	}
	// Case-insensitive fallback.
	for k, def := range meta.DrawioResources {
		if strings.ToLower(k) == key {
			return def, true
		}
	}
	return api.DrawioResourceDef{}, false
}

// ToDecoded converts a SpecComponent into the resources.DecodedResource shape
// consumed by estimate.EstimateAllResources.
//
// Lookup uses ShapeKey (full normalised key, e.g. "mxgraph.aws4.ec2_instance")
// when available, falling back to Service for backward compatibility with
// specs written before ShapeKey was introduced.
//
// When the DrawioResourceDef has a PulumiType set, attrs are inherited from
// the corresponding PulumiResourceDef in meta.PulumiResources. The drawio
// def's own Attrs then overlay those inherited values (drawio defaults win
// over pulumi defaults). User-supplied values in s.Attrs always take highest
// priority.
//
// meta is required to resolve the DrawioResourceDef for the component's
// service. When meta is nil or the service is not found in DrawioResources,
// the component is treated as NoPricing.
func (s SpecComponent) ToDecoded(defaults SpecDefaults, meta *api.MetadataResponse) (resources.DecodedResource, error) {
	provider := s.Provider
	if provider == "" {
		provider = defaults.Provider
	}
	region := s.Region
	if region == "" {
		region = defaults.Region
	}

	if s.NoPricing {
		return resources.DecodedResource{
			Provider:  provider,
			Region:    region,
			Name:      displayName(s),
			RawType:   s.Service,
			Props:     specProps(s, region),
			NoPricing: true,
		}, nil
	}

	// Use ShapeKey for lookup when available; fall back to Service for
	// backward compatibility with older spec files.
	lookupKey := s.ShapeKey
	if lookupKey == "" {
		lookupKey = s.Service
	}

	def, found := lookupDrawioDef(lookupKey, meta)
	if !found {
		// Service not in metadata — treat as no-pricing.
		return resources.DecodedResource{
			Provider:  provider,
			Region:    region,
			Name:      displayName(s),
			RawType:   s.Service,
			Props:     specProps(s, region),
			NoPricing: true,
		}, nil
	}

	// Use provider from def when not overridden by spec.
	if provider == "" && def.Provider != "" {
		provider = def.Provider
	}

	// Resolve product: prefer def.Product, fall back to pulumi def's product.
	product := def.Product

	// Build the effective attr definitions by merging pulumi def (base) with
	// drawio def (overlay). This avoids duplicating attr definitions when
	// pulumi_type is set.
	effectiveAttrs := make(map[string]api.DrawioAttrMapping)

	if def.PulumiType != "" && meta != nil {
		if pulumiDef, ok := meta.PulumiResources[def.PulumiType]; ok {
			// Inherit attrs from the pulumi def as the base layer.
			for k, pa := range pulumiDef.Attrs {
				effectiveAttrs[k] = api.DrawioAttrMapping{
					Default: pa.Default,
					Map:     pa.Map,
				}
			}
			// Inherit product from pulumi def when drawio def doesn't set one.
			if product == "" && pulumiDef.Product != "" {
				product = pulumiDef.Product
			}
		}
	}

	// Overlay drawio def attrs (drawio defaults override pulumi defaults).
	for k, da := range def.Attrs {
		effectiveAttrs[k] = da
	}

	// Build attrs: apply effective defaults, then overlay user-supplied values,
	// then apply value maps.
	attrs := make(map[string]string, len(effectiveAttrs))

	for canonicalName, attrDef := range effectiveAttrs {
		val := ""

		// User-supplied value takes priority.
		if v, ok := s.Attrs[canonicalName]; ok {
			val = strings.TrimSpace(v)
		}

		// Fall back to default from effective def.
		if val == "" && attrDef.Default != "" {
			val = attrDef.Default
		}

		// Apply value translation map if present.
		if val != "" && len(attrDef.Map) > 0 {
			val = applyDrawioValueMap(val, attrDef.Map)
		}

		if val != "" {
			attrs[canonicalName] = val
		}
	}

	// Validate: every attr defined in the effective def must have a value.
	var missing []string
	for canonicalName := range effectiveAttrs {
		if strings.TrimSpace(attrs[canonicalName]) == "" {
			missing = append(missing, canonicalName)
		}
	}
	if len(missing) > 0 {
		return resources.DecodedResource{}, fmt.Errorf(
			"component %q (%s) missing required attrs: %s",
			displayName(s), s.Service, strings.Join(missing, ", "),
		)
	}

	return resources.DecodedResource{
		Provider:    provider,
		Region:      region,
		Service:     product,
		Name:        displayName(s),
		RawType:     s.Service,
		Attrs:       attrs,
		Props:       specProps(s, region),
		PriceFilter: s.Price,
	}, nil
}

// applyDrawioValueMap translates a value using the provided map.
// Lookup is case-insensitive; if no mapping matches the original value is returned.
func applyDrawioValueMap(val string, m map[string]string) string {
	if mapped, ok := m[val]; ok {
		return mapped
	}
	lower := strings.ToLower(val)
	for k, v := range m {
		if strings.ToLower(k) == lower {
			return v
		}
	}
	return val
}

func displayName(s SpecComponent) string {
	if strings.TrimSpace(s.Label) != "" {
		return s.Label
	}
	return s.ID
}

func specProps(s SpecComponent, region string) map[string]string {
	props := map[string]string{}
	if region != "" {
		props["region"] = region
	}
	if s.Service != "" {
		props["service"] = s.Service
	}
	for k, v := range s.Attrs {
		if strings.TrimSpace(v) == "" {
			continue
		}
		props[k] = v
	}
	return props
}
